name = "TensorNetworkSimulations"
uuid = "d5f31a56-58eb-4571-b86c-9c507260a076"
repo = "git@github.com:phaerrax/TensorNetworkSimulations.git"
description = "Packages for tensor-network simulations of quantum systems."

[packages]
400a33f1-71bb-44d0-bc88-50d33f8b7a09 = { name = "QuantumCircuitSimulator", path = "Q/QuantumCircuitSimulator" }
6455c26f-8985-4381-925b-8a93509e9dbd = { name = "LindbladVectorizedTensors", path = "L/LindbladVectorizedTensors" }
b335cece-bf51-4f8f-ae23-b29b889c1946 = { name = "TEDOPA", path = "T/TEDOPA" }
f4258524-7353-4a9f-9916-8287adc6b2b5 = { name = "MarkovianClosure", path = "M/MarkovianClosure" }
